spring:
  datasource:
    url: jdbc:mysql://hadoop002:3306/movie_information?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: niit1234
    driver-class-name: com.mysql.jdbc.Driver